[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Security headers - Disabled for image loading
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-Content-Type-Options = "nosniff"
#     X-XSS-Protection = "1; mode=block"
#     Referrer-Policy = "strict-origin-when-cross-origin"
#     Cross-Origin-Opener-Policy = "same-origin"
#     Cross-Origin-Embedder-Policy = "require-corp"
#     Permissions-Policy = "geolocation=(), microphone=(), camera=()"
#     Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://kunpitch-backend-new-b63bd38838f8.herokuapp.com https://www.youtube.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https: https://*.cloudinary.com https://*.unsplash.com https://*.herokuapp.com; connect-src 'self' https://kunpitch-backend-new-b63bd38838f8.herokuapp.com https://*.youtube.com; frame-src 'self' https://www.youtube.com https://*.youtube.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; media-src 'self' https:;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 